### ISSUE TITLE
Cannot install new packages

### ISSUE THREAD

**Issue by ravikumargrk** [sanjib-sen/WebLaTex#13]
Whenever I do: 
```
root@codespaces:/workspaces/username# tlmgr install resume
```

I cannot install packages:

```
tlmgr: Local TeX Live (2021) is older than remote repository (2023).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.
```

**Comment by sanjib-sen** [comment]
Did you try upgrading it?
Anyway a major enhancement version is on the way with a lot of new features, performance boost and latest packages and there will be no issues related to this.

**Comment by ravikumargrk** [comment]
Nope. But thanks. I will close this issue for now then.
