### ISSUE TITLE
no access to copilot?

### ISSUE THREAD

**Issue by wujastyk** [sanjib-sen/WebLaTex#18]
I'm a newbie with codespace, so this is likely to be something very simple.  

When I try to install WebLaTeX as a template in my own Git account, I get errors that I don't have copilot:
```
[INFO] [auth] [2023-08-18T23:18:23.098Z] Invalid copilot token: missing token: 403 
[ERROR] [default] [2023-08-18T23:18:23.103Z] GitHub Copilot could not connect to server. Extension activation failed: "No access to GitHub Copilot found. You are currently logged in as wujastyk."
[INFO] [auth] [2023-08-18T23:18:37.087Z] Invalid copilot token: missing token: 403 
[ERROR] [default] [2023-08-18T23:18:37.088Z] GitHub Copilot could not connect to server. Extension activation failed: "No access to GitHub Copilot found. You are currently logged in as wujastyk."
[INFO] [auth] [2023-08-18T23:18:38.635Z] Invalid copilot token: missing token: 403 
[ERROR] [default] [2023-08-18T23:18:38.636Z] GitHub Copilot could not connect to server. Extension activation failed: "No access to GitHub Copilot found. You are currently logged in as wujastyk."
```

Can you advise?

**Comment by wujastyk** [comment]
Ah, I see.  I'm a faculty member , so the student pack doesn't work for me personally.  But I'll look into this more.
Thanks again!
Dominik

**Comment by sanjib-sen** [comment]
You can always buy it for a monthly subscription fee of 10 USD. It is really worth it if you are into coding, and latex works well too. 
But[ I don't recommend turning this on for sensitive projects.](https://stackoverflow.com/questions/76075204/github-copilot-and-privacy-does-github-copilot-save-locally-developed-code)
