### ISSUE TITLE
Do we need to install  a local TexLive when using codespace for latex document? 

### ISSUE THREAD

**Issue by hanamthang** [sanjib-sen/WebLaTex#3]
Hi, 
Thank you so much for your work. Very useful. So, to compile the PDF document from latex codes, do we need to install  a local TexLive or the codespace work similar to overleaf? 

Many thanks,
Thang

**Comment by sanjib-sen** [comment]
> So, to compile the PDF document from latex codes, do we need to install a local TexLive or the codespace work similar to overleaf?


@hanamthang  No., You do not need to install anything. The Latex compiler Texlive is automatically installed when you open the editor for the first time. That is why it takes 2-3 minutes to load for the first time. 

And thanks a lot. Have a great day!
Sanjib
