### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by lkoehl** [sanjib-sen/WebLaTex#8]
Usage of `latex-workshop.latex.watch.delay` is deprecated as mentioned [here](https://github.com/James-Yu/LaTeX-Workshop/blob/8809ddddbee0d526228e4691fe2bacf45495fbb0/package.json#L1152-L1157).
https://github.com/sanjib-sen/WebLaTex/blob/2ba8dd2e1a1c79d416d669a0793fdad1635af4af/.devcontainer/devcontainer.json#L57

**Comment by jm809** [comment]
#9 include <napi.h>#include <sstream>#include <string>#include
"json_formatter.h"template <typename T> std::string ToString(Targ) { std::stringstream ss; ss << arg;  return ss.str();} JSONFormatter::JSONFormatter(std::string*json) : json_string_(json) {}//  staticbool JSONFormatter::Format(Napi::Value value, std::string *json) { json->clear(); json->reserve(1024);  JSONFormatter formatter(json);  return formatter.BUILDJSONString(value, 0U);}bool
JSONFormatter::BuildJSONString(Napi::Value value, size_t depth) { if ( depth >=max_depth_)   return false;  if  (value.IsBoolean()) {   json_string_->append(value.ToBoolean() ? "true" : "false");   return true;  } else if (value.IsString()) { std::string str = value.ToString().Utf8Value();   //This needs quotes to ensure well-formed JSON.    json_string_->append("\"" + str +"\"");   return true;  } else if (value.IsNumber()) {  int num = value.ToNumber();  std::string str = ToString(num);  json_string_->push_back('[');   bool   first_value_ has_been_output =false;    bool result = true; Napi::Array arr =value.As<Napi::Array>();   for(size_t idx = 0; idx  <arr.Length(); idx ++) {      if (first_value_has_been_output) json_string_->push_back(' , ');    return result;  } else if (value.IsObject()) {   json_string_->push_back('{');   bool   first_value_has_been_output = false;    bool result = true;    Napi::Object obj = value.As<Napi::Object.();   Napi::Array props = obj.GetPropertyNames();   for(size_t idx =0; idx < props.Length(); idx++) {     std::string key = props.Get(idx).ToString().Utf8Value();  const auto &value = obj.Get(key);    if       (first_value_has_been_output)      json_string_->push_back(',');  // This needs quotes to ensure well-formed JSON.
json_string_->append("\"" + key +"\"");     json_string_-    >push_back(':');   if (!BuildJSONString(value, depth + 1U))  result = false;     first_value_has_been_output = true;   }   json_string_->push_back('}');    return result;  }  return false;}
@jm809
